# Generated by Django 2.1.3 on 2018-11-29 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
    ]
